global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ml_inference_service'
    metrics_path: '/metrics'
    static_configs:
      # host.docker.internal adalah kunci agar Docker bisa melihat Windows Anda
      - targets: ['host.docker.internal:5001'] 
        labels:
          env: 'development'
          model_name: 'your_ml_model'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']